<?php

namespace Mezian\Zaina\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{

  protected $fillable = [ 'name', 'description', 'url', 'type', 'is_draft' ];

  const TYPE_PHOTO = 'photo';
  const TYPE_VIDEO = 'video';
  const TYPE_FILE  = 'file';

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    self::creating( function ( $file ) {
//            $file->created_by = Auth::user()->id;
//            $file->modified_by = Auth::user()->id;

    } );

    self::updated( function ( $file ) {
//            $file->modified_by = Auth::user()->id;
    } );

  }

}
